config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/ideas')
  #root :to => 'static#home'
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/idea/_form.html.erb
<%= form_for @idea, :html => { :class => "form-horizontal idea" } do |f| %>

  <% if @idea.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @idea.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :picture, :class => 'form-control' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ideas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/idea/edit.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/idea/index.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= link_to idea.id, idea_path(idea) %></td>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%=l idea.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      idea_path(idea), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_idea_path(idea), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      idea_path(idea),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_idea_path,
            :class => 'btn btn-primary' %>
<button class="btn btn-primary">Yey</button>

app/views/idea/new.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/idea/show.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @idea.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @idea.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= @idea.picture %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ideas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_idea_path(@idea), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              idea_path(@idea),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => { :class => "form-horizontal idea" } do |f| %>

  <% if @idea.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @idea.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, :class => 'form-control' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ideas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/ideas/edit.html.erb
<br><br>
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

app/views/ideas/index.html.erb
<%- model_class = Idea -%>
<br><br>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-bordered">
  <thead style="background-color: #f2f2f2; color: #0d0d0d">
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%=l idea.created_at %></td>
        <td>
           <%= link_to t('.show', :default => t("helpers.links.show")),
                      idea_path(idea), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_idea_path(idea), :class => 'btn btn-success btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      idea_path(idea),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_idea_path,
            :class => 'btn btn-primary' %>

app/views/ideas/new.html.erb
<br><br>
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6" style="margin-top: 150px;">
    	<%= image_tag(@idea.picture_url, :width => 400) if @idea.picture.present? %>
    </div><br><br>
    <div class="col-sm-6" style="background-color:#f1f1f1; margin-top: 200px; margin-bottom: 50px; text-align: center;">
    	<h1><%= @idea.name %></h1>
  		<p><strong>Description: </strong><i> <%= @idea.description %></i></p>
  		<br>
    </div><center>
		<%= link_to 'Edit', edit_idea_path(@idea), :class => 'btn btn-success btn-medium' %> &nbsp;&nbsp;
		<%= link_to 'Back', ideas_path, :class => 'btn btn-primary btn-medium' %>
		</center>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Idea App" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <style type="text/css">
      a {
        color: white;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="background-color: #1a1a1a;">
  		 <div class="container">
  			 <div class="navbar-header">
  			 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
  			 <span class="sr-only">Toggle navigation</span>
  			 <span class="icon-bar"></span>
  			 <span class="icon-bar"></span>
  			 <span class="icon-bar"></span>
  			 </button>
  			 <a class="navbar-brand" href="/">The Idea app</a>
  			 </div>
  			 <div class="collapse navbar-collapse">
  			 <ul class="nav navbar-nav">
  			 <li class="active"><a href="/ideas">Ideas</a></li>
  			 </ul>
  			 </div>
  		 </div>
  	</nav>
    <div class="container">
      <%= yield %>
    </div>
    <footer>
	   <div class="container">
	     © 2017 VMMS
	   </div>
	  </footer>
	  <script src="//railsgirls.com/assets/bootstrap.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>